name: Linting

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '>=3.9 <3.14'

      - run: pip install black isort

      - run: isort --check --diff hex_modifier_tool

      - run: black --check --diff hex_modifier_tool
